"""esquema inicial

Revision ID: 7103b1c86c47
Revises: 
Create Date: 2026-08-30 19:13:35.602851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7103b1c86c47'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fcm_token', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('notificar_chollos', sa.Boolean(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_fcm_token'), 'devices', ['fcm_token'], unique=True)
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('equipo', sa.String(), nullable=False),
    sa.Column('posicion', sa.String(), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_player_source_external_id')
    )
    op.create_index(op.f('ix_players_external_id'), 'players', ['external_id'], unique=False)
    op.create_index(op.f('ix_players_source'), 'players', ['source'], unique=False)
    op.create_table('team_formations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('formacion', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'source', name='uq_formation_owner_source')
    )
    op.create_index(op.f('ix_team_formations_owner_id'), 'team_formations', ['owner_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('foto_url', sa.String(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bargain_state',
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('es_chollo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('player_id')
    )
    op.create_table('device_subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fcm_token', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fcm_token', 'player_id', name='uq_subscription_device_player')
    )
    op.create_index(op.f('ix_device_subscriptions_fcm_token'), 'device_subscriptions', ['fcm_token'], unique=False)
    op.create_index(op.f('ix_device_subscriptions_player_id'), 'device_subscriptions', ['player_id'], unique=False)
    op.create_table('points_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('jornada', sa.Integer(), nullable=False),
    sa.Column('puntos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'jornada', name='uq_points_player_jornada')
    )
    op.create_index(op.f('ix_points_history_player_id'), 'points_history', ['player_id'], unique=False)
    op.create_index(op.f('ix_points_history_source'), 'points_history', ['source'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'fecha', name='uq_price_player_fecha')
    )
    op.create_index(op.f('ix_price_history_player_id'), 'price_history', ['player_id'], unique=False)
    op.create_index(op.f('ix_price_history_source'), 'price_history', ['source'], unique=False)
    op.create_table('team_players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('slot', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'player_id', name='uq_team_owner_player'),
    sa.UniqueConstraint('owner_id', 'slot', 'source', name='uq_team_owner_slot_source')
    )
    op.create_index(op.f('ix_team_players_owner_id'), 'team_players', ['owner_id'], unique=False)
    op.create_index(op.f('ix_team_players_player_id'), 'team_players', ['player_id'], unique=False)
    op.create_index(op.f('ix_team_players_source'), 'team_players', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_players_source'), table_name='team_players')
    op.drop_index(op.f('ix_team_players_player_id'), table_name='team_players')
    op.drop_index(op.f('ix_team_players_owner_id'), table_name='team_players')
    op.drop_table('team_players')
    op.drop_index(op.f('ix_price_history_source'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_player_id'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_points_history_source'), table_name='points_history')
    op.drop_index(op.f('ix_points_history_player_id'), table_name='points_history')
    op.drop_table('points_history')
    op.drop_index(op.f('ix_device_subscriptions_player_id'), table_name='device_subscriptions')
    op.drop_index(op.f('ix_device_subscriptions_fcm_token'), table_name='device_subscriptions')
    op.drop_table('device_subscriptions')
    op.drop_table('bargain_state')
    op.drop_table('users')
    op.drop_index(op.f('ix_team_formations_owner_id'), table_name='team_formations')
    op.drop_table('team_formations')
    op.drop_index(op.f('ix_players_source'), table_name='players')
    op.drop_index(op.f('ix_players_external_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_fcm_token'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
